<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="10206" started-at="2016-06-26T09:50:01Z" finished-at="2016-06-26T09:50:11Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="10206" started-at="2016-06-26T09:50:01Z" finished-at="2016-06-26T09:50:11Z">
      <class name="sandbox.Check_functions">
        <test-method status="FAIL" signature="loadanewURL()[pri:0, instance:sandbox.Check_functions@8bd1b6a]" name="loadanewURL" duration-ms="9396" started-at="2016-06-26T10:50:01Z" finished-at="2016-06-26T10:50:11Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at com.functions.browserfactory.findelementby(browserfactory.java:14)
	at sandbox.Check_functions.loadanewURL(Check_functions.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadanewURL -->
        <test-method status="PASS" signature="readfromexcel()[pri:0, instance:sandbox.Check_functions@8bd1b6a]" name="readfromexcel" duration-ms="788" started-at="2016-06-26T10:50:11Z" finished-at="2016-06-26T10:50:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readfromexcel -->
      </class> <!-- sandbox.Check_functions -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
